/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oddevengame;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class OddEvenGame extends javax.swing.JFrame {
    static int score =0;
    static int count =0;
    
    Random r = new Random();
    int randomNum;

    /**
     * Creates new form OddEvenGame
     */
    public OddEvenGame() {
        setLocationRelativeTo(null);
        initComponents();
    }
    
    public OddEvenGame(String name){
        initComponents();
        randomNum = r.nextInt(100);
        numberLabel.setText(String.valueOf(randomNum));
        nameLabel2.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numberLabel = new javax.swing.JLabel();
        oddButton = new javax.swing.JButton();
        evenButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        scoreLabel2 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numberLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        oddButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        oddButton.setText("ODD");
        oddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oddButtonActionPerformed(evt);
            }
        });

        evenButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        evenButton.setText("EVEN");
        evenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenButtonActionPerformed(evt);
            }
        });

        scoreLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        scoreLabel.setText("SCORE");

        scoreLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        nameLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setText("MainScreen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("is Playing...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(scoreLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(oddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(evenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(scoreLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oddButtonActionPerformed
        count = count+1;
        int num = Integer.parseInt(numberLabel.getText());
        if(count==10){
            if(num%2!=0)
            {
                score++;
                scoreLabel2.setText(String.valueOf(score));
                randomNum = r.nextInt(100); 
            }
            else{
                randomNum = r.nextInt(100);
                scoreLabel2.setText(String.valueOf(randomNum));
            }
        JOptionPane.showMessageDialog(this, "Your Score is:"+ score +" /10");
        count=0;
        score=0;
        scoreLabel2.setText("");
        randomNum = r.nextInt(100);
        numberLabel.setText(String.valueOf(randomNum));
        }else{
            if(num%2!=0)
            {
                score++;
                scoreLabel2.setText(String.valueOf(score));
                randomNum = r.nextInt(100);
                numberLabel.setText(String.valueOf(randomNum));
            }else{
                JOptionPane.showMessageDialog(null, "WRONG ANSWER!");
                setLocationRelativeTo(null);
                randomNum = r.nextInt(100);
                numberLabel.setText(String.valueOf(randomNum));
            }
        }
            
    }//GEN-LAST:event_oddButtonActionPerformed

    private void evenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenButtonActionPerformed
        count = count+1;
        int num = Integer.parseInt(numberLabel.getText());
        if(count==10){
            if(num%2==0)
            {
                score++;
                scoreLabel2.setText(String.valueOf(score));
                randomNum = r.nextInt(100); 
            }
            else{
                randomNum = r.nextInt(100);
                scoreLabel2.setText(String.valueOf(randomNum));
            }
        JOptionPane.showMessageDialog(this, "Your Score is:"+ score +" /10");
        count=0;
        score=0;
        scoreLabel2.setText("");
        randomNum = r.nextInt(100);
        numberLabel.setText(String.valueOf(randomNum));
        }else{
            if(num%2==0)
            {
                score++;
                scoreLabel2.setText(String.valueOf(score));
                randomNum = r.nextInt(100);
                numberLabel.setText(String.valueOf(randomNum));
            }else{
                JOptionPane.showMessageDialog(null, "WRONG ANSWER!");
                setLocationRelativeTo(null);
                randomNum = r.nextInt(100);
                numberLabel.setText(String.valueOf(randomNum));
            }
        }
    }//GEN-LAST:event_evenButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OddEvenGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OddEvenGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OddEvenGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OddEvenGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OddEvenGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton evenButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JButton oddButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreLabel2;
    // End of variables declaration//GEN-END:variables
}
